### ISSUE TITLE
v4 support

### ISSUE THREAD

**Issue by gaborbernat** [tox-dev/tox-docker#108]
tox v4 is getting ready and we'd like to make sure this plugin is supported from day 1, we're collecting feature gaps for this under https://github.com/tox-dev/tox/issues/1974. Would be great if you could join our development chat under https://discord.gg/tox so we can assist with this. If you do so please drop in a line in the `#plugin` chat with the name of the repository you maintain. Thanks!

**Comment by dcrosta** [comment]
See branch [tox4](https://github.com/tox-dev/tox-docker/tree/tox-4) ... as of just now, tox-docker works with tox 4.0.0a9. I'll close this once I cut a release to PyPI.

**Comment by gaborbernat** [comment]
Can you make a PR with it please (draft). I want to comment in the parts where I believe we're not doing what's expected 😊

**Comment by dcrosta** [comment]
Sure -- #113

**Comment by vikahl** [comment]
What is the status of the tox4 support? Looks like it is in master, but not released on PyPI?
