### ISSUE TITLE
Any reason not to use docker==5.x.x ?

### ISSUE THREAD

**Issue by hh-h** [tox-dev/tox-docker#110]
docker==4.4.4 still supports python 2.7 with unnecessary packages.

https://docker-py.readthedocs.io/en/stable/change-log.html

**Comment by ssbarnea** [comment]
Pinning is dangerous in that context, it should happen only if while there are known/documented bugs in newer versions. If not, users will not be able benefit from newer bugfixes.

**Comment by dcrosta** [comment]
I generally pin to major versions for packages that support semver, since major versions may break things.

I haven’t gotten to testing with docker-pay 5 yet. If you have time to test and cut a PR that adds 5 to the suppprt matrix (azure config, setup.py) and if it all works I’d accept it.

**Comment by dcrosta** [comment]
Updated version now available at https://pypi.org/project/tox-docker/3.1.0/
