### ISSUE TITLE
Add options to override CMD for container

### ISSUE THREAD

**Issue by thenewguy** [tox-dev/tox-docker#114]
It would be helpful to specify the command that should be used for running the container.

[This is the example image from my use case](https://github.com/istopwg/ippsample/blob/master/Dockerfile)

The container exposes several commands via one docker image for testing purposes - in this particular case - I want to run `ippeveprinter` but there is no way to add it.

I believe it should be simply adding the option and passing it along at https://github.com/tox-dev/tox-docker/blob/ade52c44dd9199a666c2525ead471ab1323932a1/tox_docker/__init__.py#L303

**Comment by dcrosta** [comment]
This isn't supported exactly as requested, but 4.1.0 now supports building a Dockerfile in the repo:

```ini
[docker:foo]
dockerfile = {toxinidir}/path/to/Dockerfile
dockerfile_target = target  # optional, used by multi-stage builds
# don't specify image=...
```

This should be more flexible than configuration through tox.ini, and will keep the tox configuration more focused

**Comment by d9pouces** [comment]
But it requires to create a new Docker file for each required container to customize :( 
My use-case is to run MySQL, PostgreSQL and Redis with a SSL config passed through command line arguments.
Instead of just add an option to my tox.ini, I must add two options to it and create a Dockerfile for each service.

**Comment by d9pouces** [comment]
FYI, I have published a [new version of a fork](https://pypi.org/project/tox-docker-id/) that implements this option.
