### ISSUE TITLE
Invalid TravisCI Test settings, the jobs did`t use the expected Python version

### ISSUE THREAD

**Issue by nolte** [tox-dev/tox-docker#13]
Hi, 

I`m thinking, you have a small missmatch, at your Test Setup.
All the TravisCI jobs doing the same Testcases in the same configured virtual env.

For example, your Job [Python: 2.7,TOX_VERSION="tox-2.x"](https://travis-ci.org/tox-dev/tox-docker/jobs/449495604) is using [tox==3.5.3](https://travis-ci.org/tox-dev/tox-docker/jobs/449495604#L492) and [Python 2.7.14](https://travis-ci.org/tox-dev/tox-docker/jobs/449495604#L500).

Your [Python: 3.6, TOX_VERSION="tox-3.x"](https://travis-ci.org/tox-dev/tox-docker/jobs/449495609) are used the same configured virtualenv, look: [Python 2.7.14](https://travis-ci.org/tox-dev/tox-docker/jobs/449495609#L499)

**Comment by dcrosta** [comment]
Sorry, not sure how I didn't notice this when you logged it in January. Apologies for the delay.

The `TOX_VERSION` stuff is important, as tox-docker supports both tox 2 and tox 3. If you look at the `pip install` output carefully in the builds you linked to, you can see that we are installing 2.x versions in one and 3.x versions in another. I think the source of confusion is that there are actually 2 toxes involved -- the "outer one" which runs directly on travis, and starts a docker container (that's what we're most interested in testing) and an "inner one" which is installed as a dependency of tox-docker. The only thing running on the "inside" is pytest and the tox-docker tests, which don't actually use tox-docker inside of tox. (Sorry, this is confusing to talk about clearly).

The same is true of the python version being used by the "outer" tox -- it's 2.7, 3.5, and 3.6. It looks like I might not need the `envlist` at all, and just let tox use the installed python version. I'll update that, but I'm going to close this and #14.
