### ISSUE TITLE
Compatibility with tox>=3.7.0

### ISSUE THREAD

**Issue by AndrewLvov** [tox-dev/tox-docker#16]
tox 3.7.0 has a `Virtualenv` class refactored, removing `session` attribute which is used by `tox-docker` code. The latter hasn't updated and is not compatible with this `tox` version. So we have to pin `tox` until `tox-docker` gets upgraded.

```Stack trace:
  .../site-packages/pluggy/callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  .../site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  .../site-packages/tox_docker.py", line 17, in tox_runtest_pre
    action = venv.session.newaction(venv, "docker")
```

This [change](https://github.com/tox-dev/tox/commit/984ce025ad8e75e323877fb5f34128abcfba950d#diff-128f6497bdefbc956d8e8c8080964f78) removed `session` attribute as a part of `Virtualenv` class refactor, which is referenced in `tox_docker.py` [here](https://github.com/tox-dev/tox-docker/blob/master/tox_docker.py#L17)

**Comment by dcrosta** [comment]
Thanks for the report! Just pushed https://pypi.org/project/tox-docker/1.2.1/ with the fix.
