### ISSUE TITLE
Support docker 7.x

### ISSUE THREAD

**Issue by jonathangreen** [tox-dev/tox-docker#181]
Docker [7.1.0](https://github.com/docker/docker-py/releases/tag/7.1.0) contains a fix necessary to use the latest version of requests. `tox-docker` not supporting docker 7.x is keeping my project from being able to update. Would it be possible to support docker 7.x in `tox-docker`?

**Comment by jonathangreen** [comment]
I put up a small PR to resolve this one here: https://github.com/tox-dev/tox-docker/pull/182

**Comment by dcrosta** [comment]
OK, I've just published https://pypi.org/project/tox-docker/5.0.0/ with this fix.

5.0 removes support for tox 3, and has a breaking change if you were using `ports` in your tox.ini. Check the README for details on how to use the replacement.

Many thanks @jonathangreen for the contribution!
