### ISSUE TITLE
Question: how to form a URI with `expose`?

### ISSUE THREAD

**Issue by sajith** [tox-dev/tox-docker#187]
I have an application that expects a `MONGODB_CONNSTRING` environment variable, and used a `tox.ini` like below:

```
[testenv]
deps =
    [test]

commands =
    pytest

setenv =
    MONGODB_CONNSTRING = mongodb://guest:guest@localhost:27017/

[docker:mongo]
image = mongo:7.0.11
 
ports =
    27017:27017/tcp
```

In the pre-5.0.0 days of tox-docker, the above `tox.ini` worked just fine in most cases. Now that `ports` is deprecated, I am having a hard time with the new `expose` thing.  This does not work:

```
[testenv]
deps =
    [test]

commands =
    pytest

setenv:
    MONGODB_CONNSTRING = mongodb://guest:guest@localhost:{env:MONGO_PORT}/

[docker:mongo]
image = mongo:7.0.11

expose =
    MONGO_PORT=27017/tcp
```

The above does not work because tox expands  `MONGODB_CONNSTRING` to `mongodb://guest:guest@localhost:/`.  Tox does not raise an error here unlike what [the documentation](https://tox.wiki/en/latest/config.html#environment-variable-substitutions-with-default-values) says.

How can I form a `MONGODB_CONNSTRING` here?  Refactoring the application to use `MONGO_PORT` would be an inconvenience, since that code's "owner" is not me. Not everyone in the team uses tox-docker, so refactoring in that manner would be a hard-sell.  

Going back to older versions of tox-docker is also an inconvenience, because of this error:

```
"docker.errors.DockerException: Error while fetching server API version: Not supported URL scheme http+docker"
```

The above is because of [this](https://github.com/docker/docker-py/issues/3256) docker-py issue.  Now I have to pin requests at 2.31.0, which is a hassle, and may not be always possible.

**Comment by dcrosta** [comment]
Your best bet here is probably to write a wrapper script that sets the `MONGODB_CONNSTRING` env var before invoking your tests/your application. That wrapper can be the place that knows about tox-docker's env vars. Something like this might work:

```bash
#!/bin/bash

export MONGODB_CONNSTRING=mongodb://guest:guest@localhost:${MONGO_PORT}/
exec $@
```

**Comment by sajith** [comment]
@dcrosta Thank you.  I prefer going down the refactoring route, I think. That feels less "workaround-y", for lack of a better word.  Please feel free to close this issue if you need to. :-)

Do you think tox not expanding `{env:MONGO_PORT}` in the above instance is an issue that should be reported?  Perhaps it is reading comprehension failure from my part, but from the documentation it is not clear to me that environment variable substitution is not supposed to work under `setenv`.  In fact `setenv`'s description links directly to the notes about environment variable substitutions.

**Comment by dcrosta** [comment]
I agree with your reading of the docs, and that does seem like a bug, yeah. I'd report it to https://github.com/tox-dev/tox
