### ISSUE TITLE
Start different container based on env_list

### ISSUE THREAD

**Issue by marcoveeneman** [tox-dev/tox-docker#191]
Is it possible to start different containers based on env_list (or another way to setup some kind of matrix)? Like https://tox.wiki/en/latest/config.html#generative-environment-list for deps, but then with docker containers.

This would be really useful when testing an application against (for example) different database versions or different versions of < your special container >.

Take the following ini file as an example (simplified):

```ini
[tox]
env_list = 
    py3{11,12}-mysql{8,9}

[testenv:integration]
command = 
    python -m unittest tests/integration.py

docker =
    mysql8: db-mysql-8
    mysql9: db-mysql-9

[docker:db-mysql-8]
image =
    mysql:8

[docker:db-mysql-9]
image =
    mysql:9
```

I would expect that running `tox -e integration` executes the integration tests for the following 4 scenarios:
1. python 3.11 + mysql 8
2. python 3.11 + mysql 9
3. python 3.12 + mysql 8
4. python 3.12 + mysql 9

Is this (or something similar) possible with the current version of tox + tox-docker?

**Comment by dcrosta** [comment]
Almost exactly what you have here will work. You need to change `[testenv:integration]` to `[testenv]` (the base config for [generative env lists](https://tox.wiki/en/latest/config.html#generative-environment-list)), and then run. I see this output:

```bash
$ tox -c tox2.ini
# ...
py312-mysql8: install_package> python -I -m pip install --force-reinstall --no-deps /Users/dcrosta/.../tox_docker-5.0.0.post8.tar.gz
py312-mysql8: docker> run 'mysql:8' (from 'db-mysql-8')
py312-mysql8: docker> remove '3badecfebf' (from 'db-mysql-8')
py312-mysql8: OK ✔ in 3.17 seconds
py312-mysql9: install_package> python -I -m pip install --force-reinstall --no-deps /Users/dcrosta/.../tox_docker-5.0.0.post8.tar.gz
py312-mysql9: docker> run 'mysql:9' (from 'db-mysql-9')
py312-mysql9: docker> remove 'aeceb3b384' (from 'db-mysql-9')
  py312-mysql8: OK (3.17 seconds)
  py312-mysql9: OK (1.89 seconds)
  congratulations :) (5.15 seconds)```
