### ISSUE TITLE
Provide ability to keep container running

### ISSUE THREAD

**Issue by stephenfin** [tox-dev/tox-docker#38]
I think there would be some value in having a flag (a command line flag passed to `tox` directly or an environment variable, rather than a `tox.ini` setting) that would allow us to *not* auto-stop containers on cleanup. An example use case could be debugging issues you're seeing with the test-container communication. I don't imagine this would be used all that often but it would be a useful tool to have in the toolbox. I personally resorted to adding a really long sleep in my `tox.ini` to give me time to investigate the issue which is a perfectly adequate option but doesn't feel quite as _nice_.

**Comment by dcrosta** [comment]
Good idea, I like it

**Comment by stephenfin** [comment]
https://www.youtube.com/watch?v=1k8craCGpgs
