### ISSUE TITLE
Feature request: support docker-compose files

### ISSUE THREAD

**Issue by Frankkkkk** [tox-dev/tox-docker#44]
Docker-compose is sometimes use to spin-up fully running environments (database, API, etc.).

Adding this functionality to tox-docker would be useful when testing modules that need an external environment running.

Cheers

**Comment by dcrosta** [comment]
As near as I can tell, `docker-compose` exists entirely as a command-line tool. While it's implemented in Python, and I believe we could probably figure out how to call into its internals in a similar way to what the CLI tool does, this is an unmaintainable path. Alternately, `tox-docker` could just shell out, but that's straightforward with `commands_pre` / `commands_post` supported by base tox without plugins.

Between when this was filed and now, `tox-docker` has grown a set of features that might make up for some of the gaps. It's not (and shouldn't be/never will be) as full-featured as compose, but it never intended to be. So, ultimately I think this feature is not going to happen in tox-docker.
