### ISSUE TITLE
ENV's generated by tox-docker aren't accessible in the command section

### ISSUE THREAD

**Issue by BenStuart** [tox-dev/tox-docker#47]
```
pipenv run tox --version
3.14.2 imported from /home/dev/.local/share/virtualenvs/tsicorepythonservice-XHm4SvcX/lib/python3.8/site-packages/tox/__init__.py
registered plugins:
    tox-docker-1.4.1 at /home/dev/.local/share/virtualenvs/tsicorepythonservice-XHm4SvcX/lib/python3.8/site-packages/tox_docker.py
    tox-pyenv-1.1.0 at /home/dev/.local/share/virtualenvs/tsicorepythonservice-XHm4SvcX/lib/python3.8/site-packages/tox_pyenv.py

```

When trying to use `{env:KEY}` to access an environment variable generated by tox-docker as explained here: https://github.com/tox-dev/tox-docker#host-and-port-mapping

I get the error ` py38: unresolvable substitution(s): 'ECLIPSE_MOSQUITTO_HOST'. Environment variables are missing or defined recursively.`

Interestingly running `printenv`  in the `command` section returns the key `ECLIPSE_MOSQUITTO_HOST` with a value. But when tox starts it can't find the key/value, which make sense because it's not generated yet. Unfortunately setting an empty key using `setenv`to let tox run without an error. When calling the env down the line `{env:ECLIPSE_MOSQUITTO_HOST}` the key hasn't been overridden

**Comment by asottile** [comment]
hi @BenStuart, I've transferred this to `tox-docker` since I can't seem to reproduce with `tox` alone

**Comment by BenStuart** [comment]
Hi @asottile Thanks for your time.

I haven't tested to be sure but I feel this is an issue with how tox reads in environment variables as a whole. 

It looks to me like when tox starts, environment variables are read in and there is no subsequent checking for new variables down the line. As tox-docker, to my understanding, creates these variables when it's ready.

So, i'd like this issue to stay in the tox and tox-docker issues lists if possible.

**Comment by asottile** [comment]
can you provide a simple reproduction without involving `tox-docker`? thanks!

**Comment by BenStuart** [comment]
@asottile 

I don't know how `tox-docker`  passes these env vars in because I haven't been able to do it myself fiddling with scripts. mainly because the `source` command isn't recognized by the `commands` section. Throws `ERROR: InvocationError for command could not find executable source`. So I suspect the `commands` section isn't a bash shell.

Below is what I am trying to do, lets assume the `source ./export_env.bash` works in this example for explanatory purposes.`tox-docker` can somehow actually push environment variables into the whatever shell is being using in the `commands` section, so that the `printenv` shows the correct vars but `tox's` `{env:TEST_VAR}` doesn't recognize the var exists.

tox.ini

```
[tox]
envlist = py37
skipsdist = true

[testenv]
passenv =

deps =
     tox-pipenv
     pipenv
commands_pre =
     source ./export_env.bash
     printenv
commands =
     pipenv install --dev
     python3.7 -m pytest --some-arg={env:TEST_VAR}
```

export_env.bash
```

#!/bin/bash
export TEST_VAR=123
```

**Comment by asottile** [comment]
yeah `source` is a bash builtin, not a command you can run, `commands` is not a shell (shells are ~generally unsafe and non-portable)

to modify tox execution environment you'd use `setenv`

this plugin might be helpful if you're absolutely forced to use some sort of source-file? https://github.com/seanh/tox-envfile

**Comment by BenStuart** [comment]
Howdy @asottile 

That doesn't really help, looks like another way to set the environment variables when `tox` launches. Which I can do and works.

The problem is being able to pass newly created variables (ones not defined in `setenv` or exists yet) into something else in the `commands` section. This simply doesn't work with `{env:balh}`. https://github.com/taverntesting/tavern for example can use the variables `tox-docker` creates independent of when they are made, using it's own `{tavern.env.blah}` I really feel like `tox` is the limitation here.

**Comment by asottile** [comment]
ah so you just want to modify environment at runtime? have you considered writing a little python wrapper which does the necessary? something like this:

```python
import os
import sys


def main():
    os.environ['foo'] = ...
    os.execv(sys.argv[1], sys.argv[1:])

if __name__ == '__main__':
    exit(main())
```

this would let you do whatever environment mutations you'd need to do

the thing with `tox` is the configuration is parsed once at startup and then never later, the environment is immutable after `setenv` -- the thing you're asking for is kinda something that's intentionally prevented

`tavern` seems to take a different stance / approach -- but tavern is not tox ;)

**Comment by BenStuart** [comment]
Hi @asottile 
 
Sorry for the delayed reply.

I was able to work something out with a python script to take the vars tox-docker made and pass them along.

**Comment by jannylund** [comment]
Hey @BenStuart 

Could you please share the example of how you worked around this limitation.
