### ISSUE TITLE
support for AWS ECR or Gitlab hosting containers

### ISSUE THREAD

**Issue by BardiaAfshin** [tox-dev/tox-docker#48]
Is there a way to include authentication step in tox.ini when pulling docker file from AWS ECR? or any other container hosting service like Gitlab?

Right now, you have to run this command manually on the instance ```$(aws ecr get-login --no-include-email --region us-east-1)```

**Comment by dcrosta** [comment]
I don't think this falls within tox-docker's responsibility. If you need to perform some setup steps ahead of time (eg `docker pull` with certain credentials, or from a private registry, etc), that should be something you configure as a command in your CI system. Once the image exists locally, tox-docker can use it as normal.
