### ISSUE TITLE
Support container links

### ISSUE THREAD

**Issue by thenewguy** [tox-dev/tox-docker#56]
I am trying to include the elastic apm agent in integration testing.

In order to do this, I must run two services - `elastic/apm-server` and `elasticsearch`.

`elastic/apm-server` requires connectivity with `elasticsearch`

If I submit a PR for this mapping will you accept it?

**Comment by thenewguy** [comment]
@dcrosta Not sure why this one is marked `pr-rejected`?  Are you unhappy with it?

**Comment by dcrosta** [comment]
Fixed in 916f42552dae29d08f7e9ae29b5ca09f492b927a / #64
