### ISSUE TITLE
Feature Request: Settable hostnames and user-defined bridge network

### ISSUE THREAD

**Issue by stantonk** [tox-dev/tox-docker#7]
In some integration testing contexts it can be helpful to be able to have multiple containers interact with one another in addition to the host machine. This can be achieved in a hacky way by using the python [docker](https://pypi.org/project/docker/) driver library that tox already leverages, and parsing out the IP address for each container.

It would be nicer to be able to specify the hostnames of each container tox-docker spins up, and have them all be part of a [user-defined bridge network](https://docs.docker.com/network/network-tutorial-standalone/#use-user-defined-bridge-networks). This would enable hostname resolution and make it easier to write integration tests where multiple containers are involved and need to talk between each other.

**Comment by dcrosta** [comment]
Does [docker-compose](https://github.com/docker/compose) already do what you need here? Since it's written in Python (TIL), it's presumably possible to use it from tox-docker. Offering compose functionality, rather than one-off-ing features for more complicated setups, would be a great improvement for tox-docker.

**Comment by stantonk** [comment]
@dcrosta it does indeed, your suggested approach makes much more sense! I hadn't explored the existing python docker library in detail, nor was I aware docker-compose is implemented in Python either.

I'll poke around a bit and see what might make this more straightforward.

**Comment by dcrosta** [comment]
Cool -- let me know what you learn! I probably won't have time to work on this in the next few weeks, but I'm definitely open to contributions :)

**Comment by dcrosta** [comment]
I think this will be fixed by #56? If you agree @stantonk let me know or feel free to close this as a duplicate.

**Comment by dcrosta** [comment]
Closing this as #64 has landed, and #44 tracks the request to support docker-compose.
