### ISSUE TITLE
Allow relative path in mounted dirs

### ISSUE THREAD

**Issue by d9pouces** [tox-dev/tox-docker#90]
Currently, the syntax  `bind:rw:/my/own/datadir:/var/lib/postgresql/data` only allows absolute paths for the host path.
It should be easy to accept relative paths (transforming them into absolute paths before the Docker call)

**Comment by dcrosta** [comment]
You can use tox substitutions to achieve the same result with greater explicitness, eg https://github.com/tox-dev/tox-docker/blob/master/tox.ini#L61

**Comment by d9pouces** [comment]
You're right, thanks for the tip!
